# language: python
# python:
# -'3.4'
# install: 'pip install -r requirements.txt'
# script:
# - SECRET_KEY="whatever" ./manage.py test
language: python

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DEVELOPMENT=true
        - HOSTNAME='0.0.0.0'
        - IP='0.0.0.0'
        - PORT='5000'
        - SECRET_KEY='whatever'

install: "pip install -r requirements.txt"